name: Check Arduino

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          project-type: library
          library-manager: false
          compliance: specification
